export const Constants = {
  CURRENT_PAGE: 1,
  ROWS_ON_PAGE: 10,
  MAX_SIZE: 10,
  MAX_IMAGE: 5,
  MAP_ZOOM: 15,
  SCAN: "scan",
  MAP_LIBRARIES: 'places',
  TOKEN: 'token',
  SHOP_TIME: 'storeTime',
  SID: 'sid',
  CATEGORYID: 'categoryid',
  SHOP_DETAILS: 'storeDetails',
  NO_INTERNET_CONNECTION_MSG: 'No internet connection!',
  GROCERIES_LOGO: '../../../assets/images/groceriesicon.png',
  STORE_LOGO_UPLOAD: '../../../assets/images/uploadLogo.png',
  REGEX: {
    EMAIL_PATTERN: new RegExp(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/),
    PASSWORD_PATTERN: new RegExp(
      /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#])[A-Za-z\d@$!%*?&#]{6,16}$/,
    ),
    PHONE_PATTERN: new RegExp(/^([0-9]{10,10})$/),
    UPC_PATTERN: new RegExp(/^(?=.*0)[0-9]{12}$/)
  },
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 16,
  WEEKDAY_OPEN: 'weekdayOpen',
  WEEKDAY_CLOSE: 'weekdayClose',
  SATURDAY_OPEN: 'saturdayOpen',
  SATURDAY_CLOSE: 'saturdayClose',
  SUNDAY_OPEN: 'sundayOpen',
  SUNDAY_CLOSE: 'sundayClose',
  TIME_VARIABLES: {
    maxWeekdayOpen: '23:59',
    minWeekdayClose: '00:01',
    maxSaturdayOpen: '23:59',
    minSaturdayClose: '00:01',
    maxSundayOpen: '23:59',
    minSundayClose: '00:01',
  },
};

export const URL_ROUTES = {
  LOGIN: '',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  SIGN_UP: '/sign-up',
  SET_TIME: '/set-time',
  STORE_HOME: '/store/products',
  PRODUCT_PRE_DETAIL: 'store/products/',
  PRODUCT_ADD_EDIT: 'store/products/add-edit',
  PRODUCT_DETAIL: '/detail',
  STORE: 'store/',
  CHANGE_PASSWORD: 'store/change-password',
  STORE_DETAIL: 'store/detail/',
  STORE_EDIT: '/edit/',
  ADMIN_HOME: 'admin/home',
  PRODUCT_REVIEW: 'store/product/review',
  BATCH_UPLOAD: 'store/batch-upload'
};
