stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - dist-dev/
  - dist-stage/
  - dist-prod/

build_development:
  stage: build
  script:
  - npm install
  - npm run build-development
  only: ['development']

build_stage:
  stage: build
  script:
  - npm install
  - npm run build-stage
  only: ['stage']
  
build_Producttion:
  stage: build
  script:
  - npm install
  - npm run build-prod
  only: ['master']
  
deploy_development:
  stage: deploy
  script:
  - rsync -zvhr -e ssh dist-dev/ ubuntu@$Dev_Server_IP:/var/sites/dev/ixoop-store-angular/
  only: ['development']
  
deploy_stage:
  stage: deploy
  script:
  - rsync -zvhr -e ssh dist-stage/ ubuntu@$Dev_Server_IP:/var/sites/stage/ixoop-store-angular/
  only: ['stage']
  
deploy_Production:
  stage: deploy
  script:
  - rsync -zvhr -e ssh dist-prod/ ubuntu@$Prod_Server_IP:/var/sites/ixoop-store-angular/
  only: ['master']

